---
- name: Install libvirt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - bridge-utils
    - cpu-checker
    - libvirt-clients
    - libvirt-daemon
    - libvirt-daemon-system
    - libosinfo-bin
    - qemu-kvm
    - virtinst
    - virt-manager
  become: yes
  become_method: sudo

- name: Enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
  become: yes
  become_method: sudo
